trigger:
  branches:
    include:
      - main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version you want to use
    addToPath: true

- script: |
    pip install -r requirements.txt  # Install Python dependencies
  displayName: 'Install dependencies'

- script: |
    # Add your build commands here (e.g., migrations, collectstatic, etc.)
    python manage.py migrate
    python manage.py collectstatic --noinput
  displayName: 'Build Python application'
